version: '3.8'

services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"    # For Docker internal clients, optional for host if no external access
      - "29092:29092"  # For host machine clients
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  kafkaui:
    image: redpandadata/console:latest
    container_name: kafkaui
    environment:
      KAFKA_BROKERS: broker:9092
    ports:
      - 8080:8080
    depends_on:
      - broker

  topic-init:
    image: apache/kafka:latest
    container_name: topic-init
    depends_on:
      - broker
    entrypoint: [ "sh", "-c" ]
    command: >
      "
      echo 'Waiting for Kafka to be ready...' &&
      while ! nc -z broker 9092; do sleep 1; done &&
      echo 'Kafka is ready. Creating topic...' &&
      /opt/kafka/bin/kafka-topics.sh --create --topic my-topic --bootstrap-server broker:9092 --partitions 3 --replication-factor 1 ||
      echo 'Topic already exists'
      "